# Generated by Django 5.1.2 on 2024-11-01 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_mode',
            field=models.CharField(choices=[('Phone', 'Phone'), ('EMail', 'EMail')], default='EMail', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_assigned_to_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastmodified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', max_length=5),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Compatibility Issue', 'Comaptibility Issue'), ('General', 'Geberal')], default='General', max_length=20),
        ),
    ]
