# Generated by Django 5.1.2 on 2024-11-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
