# Generated by Django 5.1.2 on 2024-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_resolution_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_mode',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], default='Email', max_length=20),
        ),
    ]
