# Generated by Django 5.1.2 on 2024-11-03 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='contact_mode',
        ),
    ]
