# Generated by Django 5.1.2 on 2024-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
