# Generated by Django 5.1.2 on 2024-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_resolution_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=5),
        ),
    ]
